version: "2.3"

volumes:
  logica-sandbox-volume:

services:
  keycloak:
    image: jboss/keycloak
    volumes:
      - "./realm_properties.json:/etc/security/realm_properties.json"
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/etc/security/realm_properties.json
    command:
      [
        "-Djboss.http.port=8080",
        "-Dkeycloak.profile.feature.upload_scripts=enabled",
      ]

  sandbox-mysql:
    image: logicahealth/sandbox-mysql
    ports:
      - "3306:3306"
    volumes:
      - logica-sandbox-volume:/var/lib/mysql57
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "/wait-for-db.sh"]
      interval: 2s
      timeout: 30s
      retries: 20

  sandbox-manager-api:
    image: logicahealth/sandbox-manager-api
    ports:
      - "12000:12000"
    environment:
      - DB_HOST=sandbox-mysql
      - DB_PORT=3306
      - DB_NAME=sandman
      - DB_USER=root
      - DB_PASSWORD=password
      - AUTH_HOST=sandbox
      - AUTH_PORT=8060
      - API_DSTU2_HOST=dstu2
      - API_STU3_HOST=stu3
      - API_R4_HOST=r4
      - API_R5_HOST=r5
    depends_on:
      sandbox-mysql:
        condition: service_healthy

  sandbox:
    build:
      context: ../sandbox-manager-v3
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "3001:3001"
      - "8060:8060"
    environment:
      - AUTH_HOST=sandbox
      - AUTH_PORT=8060
      - DB_NAME=oic
      - DB_HOST=sandbox-mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - SHOW_SQL=true
      - API_DSTU2_HOST=dstu2
      - API_DSTU2_PORT=8078
      - API_STU3_HOST=stu3
      - API_STU3_PORT=8079
      - API_R4_HOST=r4
      - API_R4_PORT=8070
      - PATIENT_PICKER_HOST=localhost
      - PATIENT_PICKER_PORT=8094
      - SANDMAN_API_HOST=sandbox-manager-api
      - SANDMAN_API_PORT=12000
      - SPRING_PROFILES_ACTIVE=users-keycloak,local
      - KEYCLOAK_REALM=Development
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
      - KEYCLOAK_SSL_REQUIRED=none
      - KEYCLOAK_CREDENTIALS=593ada9c-b1dc-444f-a2e6-30cc4add8146
      - KEYCLOAK_LOGOUT_SUCCESS_URL=http://keycloak:8080/auth/realms/Development/protocol/openid-connect/logout?redirect_uri=http://localhost:3001
      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,address=5060,server=y,suspend=n"
    depends_on:
      sandbox-mysql:
        condition: service_healthy

  dstu2:
    image: logicahealth/api
    ports:
      - "8078:8078"
    environment:
      - SPRING_PROFILES_ACTIVE=dstu2,multitenant
      - API_PORT=8078
      - SANDBOX_NAME=hspc8
      - SBMA_HOST=sandbox-manager-api
      - SBMA_PORT=12000
      - DB_HOST=sandbox-mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - AUTH_HOST=sandbox
      - AUTH_PORT=8060
      - MANIFEST_OVERRIDE=false
    depends_on:
      sandbox-mysql:
        condition: service_healthy

  stu3:
    image: logicahealth/api
    ports:
      - "8079:8079"
    environment:
      - SPRING_PROFILES_ACTIVE=stu3,multitenant
      - API_PORT=8079
      - SANDBOX_NAME=hspc9
      - SBMA_HOST=sandbox-manager-api
      - SBMA_PORT=12000
      - DB_HOST=sandbox-mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - AUTH_HOST=sandbox
      - AUTH_PORT=8060
      - MANIFEST_OVERRIDE=false
    depends_on:
      sandbox-mysql:
        condition: service_healthy

  r4:
    image: logicahealth/api
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=r4,multitenant
      - API_PORT=8070
      - SANDBOX_NAME=hspc10
      - SBMA_HOST=sandbox-manager-api
      - SBMA_PORT=12000
      - DB_HOST=sandbox-mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - AUTH_HOST=sandbox
      - AUTH_PORT=8060
      - MANIFEST_OVERRIDE=false
    depends_on:
      sandbox-mysql:
        condition: service_healthy

  r5:
    image: logicahealth/api
    ports:
      - "8071:8071"
    environment:
      - SPRING_PROFILES_ACTIVE=r5,multitenant
      - API_PORT=8071
      - SANDBOX_NAME=hspc11
      - SBMA_HOST=sandbox-manager-api
      - SBMA_PORT=12000
      - DB_HOST=sandbox-mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - AUTH_HOST=sandbox
      - AUTH_PORT=8060
      - MANIFEST_OVERRIDE=false
    depends_on:
      sandbox-mysql:
        condition: service_healthy

  static-content:
    image: logicahealth/sandbox-ce-static-content
    ports:
      - "8090:80"

  bilirubin-risk-chart:
    image: logicahealth/bilirubin-risk-chart-app
    ports:
      - "8086:8086"

  patient-data-manager:
    image: logicahealth/patient-data-manager
    ports:
      - "8096:8096"
